
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  ms1:
    image: ms/type-detector
    build: ./microservices/smsh_type_detector
    container_name: ms1
    ports:
      - "8001:8000"
      - "2201:2222"
    privileged: false
    restart: unless-stopped

  ms2:
    image: ms/name-entities
    build: ./microservices/smsh_name_entities
    container_name: ms2
    ports:
      - "8002:8000"
      - "2202:2222"
    privileged: false
    restart: unless-stopped

  ms3:
    image: ms/html-grabber
    build: ./microservices/smsh_html_grabber
    container_name: ms3
    ports:
      - "8003:8000"
      - "2203:2222"
    privileged: false
    restart: unless-stopped

  ms4:
    image: ms/campaign-identifier
    build: ./microservices/smsh_campaign_identifier
    container_name: ms4
    ports:
      - "8004:8000"
      - "2204:2222"
    depends_on:
      - mongo
    privileged: false
    restart: unless-stopped


volumes:
  mongodata:

