
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  ms1:
    image: ms/type-detector
    build:  
      context: .
      dockerfile: microservices/smsh_ia_models/Dockerfile

    container_name: ms1
    ports:
      - "8001:8000"
      - "2201:2222"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./logger_config:/app/logger_config
    privileged: false
    restart: unless-stopped

  ms2:
    image: ms/html-grabber
    build:
      context: .
      dockerfile: microservices/smsh_html_grabber/Dockerfile

    container_name: ms2
    ports:
      - "8002:8000"
      - "2202:2222"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./logger_config:/app/logger_config
    privileged: false
    restart: unless-stopped

  ms3:
    image: ms/campaign-identifier
    build: 
      context: .
      dockerfile: microservices/smsh_campaign_identifier/Dockerfile

    container_name: ms3
    ports:
      - "8003:8000"
      - "2203:2222"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./logger_config:/app/logger_config
    depends_on:
      - mongo
    privileged: false
    restart: unless-stopped


volumes:
  mongodata:

